export const DOWNLOADING_DATA = "DOWNLOADING_DATA"
export const DOWNLOADING_DATA_SUCCESS = "DOWNLOADING_DATA_SUCCESS"
export const DOWNLOADING_DATA_FAILURE = "DOWNLOADING_DATA_FAILURE"

export const CREATING_PLAYLIST = "CREATING_PLAYLIST"
export const CREATING_PLAYLIST_SUCCESS = "CREATING_PLAYLIST_SUCCESS"
export const CREATING_PLAYLIST_FAILURE = "CREATING_PLAYLIST_FAILURE"

export const EDITING_PLAYLIST = "EDITING_PLAYLIST"
export const EDITING_PLAYLIST_SUCCESS = "EDITING_PLAYLIST_SUCCESS"
export const EDITING_PLAYLIST_FAILURE = "EDITING_PLAYLIST_FAILURE"

export const DELETING_PLAYLIST = "DELETING_PLAYLIST"
export const DELETING_PLAYLIST_SUCCESS = "DELETING_PLAYLIST_SUCCESS"
export const DELETING_PLAYLIST_FAILURE = "DELETING_PLAYLIST_FAILURE"

export const ADDING_VIDEOS = "ADDING_VIDEOS"
export const ADD_VIDEOS_SUCCESS = "ADD_VIDEOS_SUCCESS"
export const ADD_VIDEOS_FAILURE = "ADD_VIDEOS_FAILURE"